# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoringApp', '0002_auto_20170820_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ourusers',
            new_name='usr',
        ),
    ]
